displayName=Extended Bank Search
author=khendricksen
description=Search your bank by equipment stats, slot, warmth and food, straight from the native search box
tags=bank,search,stat,stats,slot,equipment,gear,armour,armor,warm,wintertodt,food
plugins=com.github.khendricksen.extendedbanksearch.ExtendedBankSearchPlugin
build=standard